# 3.3 text similarity

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

sent = ("휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.", "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니 다.") 

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sent) # 문장 벡터화 진행
print(tfidf_matrix)

  (0, 12)	0.3160304990863645
  (0, 6)	0.3160304990863645
  (0, 4)	0.3160304990863645
  (0, 1)	0.3160304990863645
  (0, 9)	0.3160304990863645
  (0, 14)	0.22485830296545706
  (0, 8)	0.3160304990863645
  (0, 13)	0.3160304990863645
  (0, 5)	0.3160304990863645
  (0, 7)	0.3160304990863645
  (0, 17)	0.22485830296545706
  (1, 11)	0.35327776613855977
  (1, 16)	0.35327776613855977
  (1, 3)	0.35327776613855977
  (1, 10)	0.35327776613855977
  (1, 0)	0.35327776613855977
  (1, 2)	0.35327776613855977
  (1, 15)	0.35327776613855977
  (1, 14)	0.2513600402461016
  (1, 17)	0.2513600402461016


In [7]:
idf = tfidf_vectorizer.idf_
print(dict(zip(tfidf_vectorizer.get_feature_names(), idf))) # 각 수치에 대한 값 시각화

{'갑작스런': 1.4054651081081644, '내일': 1.4054651081081644, '놀러왔다가': 1.4054651081081644, '망연자실': 1.4054651081081644, '반가운': 1.4054651081081644, '서쪽': 1.4054651081081644, '소식': 1.4054651081081644, '오늘': 1.4054651081081644, '으로': 1.4054651081081644, '이어졌는데요': 1.4054651081081644, '인해': 1.4054651081081644, '있습니': 1.4054651081081644, '있습니다': 1.4054651081081644, '중심': 1.4054651081081644, '폭염': 1.0, '피해서': 1.4054651081081644, '하고': 1.4054651081081644, '휴일': 1.0}


## Jaccard similarity

In [8]:
import numpy as np

In [9]:
from sklearn.metrics import jaccard_score

jaccard_score(np.array([1,1,0,0]), np.array([1,1,0,2]), average=None)

array([0.5, 1. , 0. ])

## Cosine similarity

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[0.11304078]])

## Euclidean similarity

In [11]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2])

def l1_normalize(v):
    norm = np.sum(v)
    return v / norm

tfidf_norm_l1 = l1_normalize(tfidf_matrix)
euclidean_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.21243357]])

## Manhattan similarity

In [12]:
from sklearn.metrics.pairwise import manhattan_distances

manhattan_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.85654185]])